// Generated by CIRCT firtool-1.114.1
`include "verification/layers-Alu-Verification.sv"
`ifndef layers_Alu_Verification_Assert
`define layers_Alu_Verification_Assert
`endif // layers_Alu_Verification_Assert
