// Generated by CIRCT firtool-1.114.1
`include "verification/layers-PE-Verification.sv"
`ifndef layers_PE_Verification_Assert
`define layers_PE_Verification_Assert
`endif // layers_PE_Verification_Assert
